apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xclusters.compositions.io
spec:
  group: compositions.io
  names:
    kind: XCluster 
    plural: xclusters
  claimNames:
    kind: GKECluster
    plural: gkeclusters
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  clusterName:
                    type: string
                  region:
                    type: string
                  machineType:
                    type: string
                  nodeCount:
                    type: number
              compositionRef:
                type: object
                properties:
                  name:
                    type: string
                    enum:
                      - gke-cluster-nodepool
