name: Destroy an APP with its repo

on:
  workflow_dispatch:
    inputs:
      apiName:
        description: 'API Name'
        required: true
      repoURLforArgo: 
        description: 'The URL of the repository to be destroyed'
        required: true

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Argo CD CLI
      run: |
        sudo curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        sudo chmod +x /usr/local/bin/argocd

    - name: Login to Argo CD
      run: argocd login ${{ secrets.ARGOCD_SERVER }} --username ${{ secrets.ARGOCD_USER }} --password ${{ secrets.ARGOCD_PASS }} --grpc-web

    - name: Destroy API
      run: |
          argocd app delete ${{ github.event.inputs.apiName }} --cascade --grpc-web -y

    - name: Unregister Repository from Argo CD
      run: argocd repo rm ${{ github.event.inputs.repoURLforArgo }} --grpc-web

    - name: Delete GitHub Repository
      run: |
          echo "${{ github.event.inputs.repoURLforArgo }}"
          REPO_NAME=$(echo "${{ github.event.inputs.repoURLforArgo }}" | sed 's/.*\/\([^ ]*\/[^.]*\).*/\1/')
          echo "$REPO_NAME"
          curl -X DELETE -H "Authorization: token ${{ secrets.MYMYGITHUB_TOKEN }}" \
          https://api.github.com/repos/${REPO_NAME}